export const questions  = 
    [
        ["My father", "Aby"],
        ["Mountain", "Jabal"],
        ["Door", "Bab"], 
        ["Duck", "Batta"],
        ["House", "Bayt"],
        ["Girl", "Bint"],
        ["Write", "Aktub"],
        ["I", "Ana"],
        ["My mother", "Ummy"],
        ["My brother", "Akhy"],
        ["My sister", "Ukhty"],
        ["Grandfather", "Jaddy"],
        ["Grandmother", "Jaddaty"],
        ["Dates", "Tamr"],
        ["Crocodile", "Timsah"],
        ["Apple", "Tuffah"],
        ["Figs", "Teen"],
        ["Notebook", "Dafftar"],
        ["Big (male)", "Kabeer"],
        ["Small (male)", "Sagheer"],
        ["Big (female)", "Kabeerah"],
        ["Small (female)", "Sagheerah"],
        ["Tall (female)","Taweelah"],
        ["Short (female)","Quaseerah"],
        ["Tall (male)","Taweel"],
        ["Short (male)","Quaseer"],
        ["Fox","Tha’lab"],
        ["Snake","Thu’ban"],
        ["Fruits","Thimar"],
        ["Eat","Akul"],
        ["Like","Uhib"],
        ["Red","Ahmar"],
        ["Yellow","Asfar"],
        ["Green","Akhdar"],
        ["Blue","Azraq"],
        ["Color","Lawn"],
        ["Camel","Jamal"],
        ["Cheese","Jubn"],
        ["Bridge","Jesr"],
        ["Hen (Chicken)","Dajajah"],
        ["Neighbors","Jeeran"],
        ["Stars","Nujoom"],
        ["Want","Ureed"],
        ["Black","Aswad"],
        ["White","Abyad"],
        ["Book","Kitab"],
        ["Chair","Kursy"],
        ["Pen","Qalam"],
        ["Flag","A’lam"],
        ["Horse","Hisan"],
        ["Seeds","Huboob"],
        ["Milk","Haleeb"],
        ["Bus","Hafilah"],
        ["Whale","Hoot"],
        ["Drink","Ashrab"],
        ["Board","Sabboorah"],
        ["Write","Yaktub"],
        ["Pink","Wardy"],
        ["Orange","Burtoqaly"],
        ["Brown","Bunny"],
        ["Purple","Banafsajy"],
        ["Bag","Haqeebah"],
        ["He","Huwa"],
        ["Sheep","Kharoof"],
        ["Peach","Khawkh"],
        ["Bread","Khubz"],
        ["Cucumber","Khiyar"],
        ["Ring","Khatam"],
        ["Incense","Bakhoor"],
        ["Palms","Nakheel"],
        ["Hand","Yad"],
        ["School","Madrasah"],
        ["Classroom","Saff"],
        ["Go","Athhab"],
        ["to (direction)","Ila"],
        ["Beautiful","Jameel"],
        ["Bear","Dub"],
        ["Dirham","Dirham"],
        ["Study","Adrus"],
        ["Worm","Doodah"],
        ["Garden","Hadeeqah"],
        ["Pupil","Tilmeeth"],
        ["Table","Tawelah"],
        ["Above","Fawq"],
        ["Under","Taht"],
        ["Beside","Bijaneb"],
        ["but","Laken"],
        ["where","Ayn"],
        ["Tail","Thail"],
        ["Corn","Thurah"],
        ["Wolf","Thi’b"],
        ["Shoes","Hithaa’"],
        ["Arm","Thiraa’"],
        ["Seeds","Buthoor"],
        ["Delicious","Latheeth"],
    
        ["Head","Raa’s"],
        ["Pomegranate","Rumman"],
        ["Leg","Rijl"],
        ["Butterfly","Farashah"],
        ["Happy","Masroor"],
        ["Feather","Reeshah"],
        ["Monkey","Qird"],
        ["Behind","Qalf"],
        ["In front of","Amam"],
        ["Teacher","Mua’llem"],
    ];